baseURL = "https://syncpoint.github.io/odin-manual"
languageCode = "en-us"
title = "ODIN - Handbuch"
 
[params]
  [params.navigation]
    help = "Help"
    back = "Zurück"
    Content = "Inhalt"
     
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1

[menu]
[[menu.main]]
    identifier = "Auf einer Steite"
    name = "Auf einer Steite"
    pre = "<i class='fa fa-heart'></i>"
    url = "/onepage/"
    weight = 1    
[[menu.main]]
    identifier = "Handbuch"
    name = "Handbuch"
    pre = "<i class='fa fa-heart'></i>"
    url = "/"
    weight = -110

