baseURL = "https://syncpoint.github.io/odin-manual"
languageCode = "de-DE"
title = "ODIN - Handbuch"
defaultContentLanguage = "de"

[params]
  version = "0.10.1" 
  version-date = "31.05.2021"
     
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1
 
[languages]
  [languages.de]
    contentDir = "content/de"
    languageName = "Deutsch"
    weight = 1
  [languages.de.params]
    flag = "de"
    title = "ODIN - Handbuch"
  
  [[languages.de.menu.main]]
    identifier = "Handbuch"
    name = "Handbuch"
    pre = "<i class='fa fa-heart'></i>"
    url = "/"
    weight = -110
  
     
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 2
  [languages.en.params]
    flag = "en"
    title = "ODIN - Manual"

[[languages.en.menu.main]]
    identifier = "Manual"
    name = "Manual"
    pre = "<i class='fa fa-heart'></i>"
    url = "/"
    weight = -110